sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tEQ57AEKMrhZTMAVg2N
    access-key-secret: FhbrmsxXZDDEkxokjS6OGiGDWAFHjV
    bucket-name: apang
  redis:
    host: 47.109.184.51
    port: 6379
    password: 123456
  wechat:
    appid: wxa86ca1de27bd710d
    secret: 8497d6c27dcb158750ee58302e6e22b1

